samples:
    # specifies expected location of split reads
    raw_bam_list: [data/raw_in_samples.bam.list]
    shifted_bam_list: [data/shifted_in_samples.bam.list]
    id: "9498"
# modules:
#     # Should snakemake do stlfr specific analyses, false if the library isn't of linked reads
#     mapping: True

params:
    # path to the snakemake file
    smk_path: "/XYFS01/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_2/BIGDATA2/gzfezx_shhli_2/USER/luozhenyu/script/mitoquest_smk/smkfile"
    # path to the reference directory
    ref_dir: "/XYFS01/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_2/BIGDATA2/gzfezx_shhli_2/database/GRCh38_chrM_rCRS"
    # reference
    shifted_ref_fa: "/XYFS01/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_2/BIGDATA2/gzfezx_shhli_2/database/GRCh38_chrM_rCRS/Homo_sapiens.GRCh38.chrM_rCRS.shifted_by_8000_bp.fa"
    raw_ref_fa: "/XYFS01/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_2/BIGDATA2/gzfezx_shhli_2/database/GRCh38_chrM_rCRS/Homo_sapiens.GRCh38.chrM_rCRS.fa"
    # path to mitoquest tool
    mitoquest: "/HOME/gzfezx_shhli/gzfezx_shhlixy_3/BioSoftware/local/bin/mitoquest"
    # annotation database
    annotation_dir: "/XYFS01/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_2/BIGDATA2/gzfezx_shhli_2/software/mitoquest/data"
    # path to some analysis scripts directory
    scripts_dir: "/XYFS01/HDD_POOL/gzfezx_shhli/gzfezx_shhlixy_2/BIGDATA2/gzfezx_shhli_2/software/mitoquest/tools"
    # path to the python
    python: "/HOME/gzfezx_shhli/gzfezx_shhlixy_2/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/pacbio/bin/python"
    # the parameters for mitoquest
    # the mapping quality cutoff for mitoquest
    mapQ: 20
    # the base quality cutoff for mitoquest
    baseQ: 20

threads:
    64